version: '3.8'

services:
    app:
        container_name: visma-app
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./:/var/www/hk-2022/
            - visma-vendor:/var/www/hk-2022/vendor/
            - visma-node_modules:/var/www/hk-2022/node_modules/
        networks:
            - default
    webserver:
        image: nginx:latest
        container_name: visma-webserver
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www/hk-2022/
            - visma-vendor:/var/www/hk-2022/vendor/
            - visma-node_modules:/var/www/hk-2022/node_modules/
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - '80:80'
            - '8000:80'
            - '443:443'
        networks:
            - default
    mysql-db:
        image: mysql:8.0.28
        container_name: visma-mysql-db
        restart: unless-stopped
        tty: true
        volumes:
            - visma-db-data:/var/lib/mysql/
        environment:
            MYSQL_USER: app
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: hk
        networks:
            - default

networks:
    default:
        driver: bridge

volumes:
    visma-vendor:
        driver: local
    visma-node_modules:
        driver: local
    visma-db-data:
        driver: local
